//
//  File.swift
//  
//
//  Created by smis on 2022/01/11.
//

import UIKit

public struct LineIcon {
    public static let close2448 = UIImage(named: "ic_close_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let delete2448 = UIImage(named: "ic_delete_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let back2448 = UIImage(named: "ic_back_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let forward2448 = UIImage(named: "ic_forward_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let checkmark2448 = UIImage(named: "ic_checkmark_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let preview2448 = UIImage(named: "ic_preview_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let search2448 = UIImage(named: "ic_search_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let moreHorizon2448 = UIImage(named: "ic_more_horizon_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let moreVertical2448 = UIImage(named: "ic_more_vertical_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let subsetting2448 = UIImage(named: "ic_subsetting_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let info2448 = UIImage(named: "ic_info_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let edit2448 = UIImage(named: "ic_edit_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let close2424 = UIImage(named: "ic_close_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let delete2424 = UIImage(named: "ic_delete_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let back2424 = UIImage(named: "ic_back_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let forward2424 = UIImage(named: "ic_forward_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let checkmark2424 = UIImage(named: "ic_checkmark_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let preview2424 = UIImage(named: "ic_preview_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let search2424 = UIImage(named: "ic_search_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let moreHorizon2424 = UIImage(named: "ic_more_horizon_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let moreVertical2424 = UIImage(named: "ic_more_vertical_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let subsetting2424 = UIImage(named: "ic_subsetting_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let info2424 = UIImage(named: "ic_info_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let edit2424 = UIImage(named: "ic_edit_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let drag2424 = UIImage(named: "ic_drag_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let skip2424 = UIImage(named: "ic_skip_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let copy2424 = UIImage(named: "ic_copy_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let repeat2424 = UIImage(named: "ic_repeat_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let faq2424 = UIImage(named: "ic_faq_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let add2424 = UIImage(named: "ic_add_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let under2424 = UIImage(named: "ic_under_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let go2424 = UIImage(named: "ic_go_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let undo2424 = UIImage(named: "ic_undo_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let reset2424 = UIImage(named: "ic_reset_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let share2424 = UIImage(named: "ic_share_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let close1616 = UIImage(named: "ic_close_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let delete1616 = UIImage(named: "ic_delete_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let back1616 = UIImage(named: "ic_back_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let forward1616 = UIImage(named: "ic_forward_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let checkmark1616 = UIImage(named: "ic_checkmark_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let preview1616 = UIImage(named: "ic_preview_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let search1616 = UIImage(named: "ic_search_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let moreHorizon1616 = UIImage(named: "ic_more_horizon_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let moreVertical1616 = UIImage(named: "ic_more_vertical_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let subsetting1616 = UIImage(named: "ic_subsetting_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let info1616 = UIImage(named: "ic_info_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let edit1616 = UIImage(named: "ic_edit_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let drag1616 = UIImage(named: "ic_drag_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let skip1616 = UIImage(named: "ic_skip_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let copy1616 = UIImage(named: "ic_copy_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let repeat1616 = UIImage(named: "ic_repeat_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let faq1616 = UIImage(named: "ic_faq_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let add1616 = UIImage(named: "ic_add_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let under1616 = UIImage(named: "ic_under_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let go1616 = UIImage(named: "ic_go_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
}
