//
//  SolidIcon.swift
//  
//
//  Created by smis on 2022/01/11.
//

import Foundation

public struct SolidIcon {
    public static let fullpopupClose2448 = UIImage(named: "ic_fullpopup_close_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let soundOn2448 = UIImage(named: "ic_sound_on_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let soundOff2448 = UIImage(named: "ic_sound_off_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let label2448 = UIImage(named: "ic_label_24_48", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let soundOn2424 = UIImage(named: "ic_sound_on_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let soundOff2424 = UIImage(named: "ic_sound_off_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let label2424 = UIImage(named: "ic_label_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let snooze2424 = UIImage(named: "ic_snooze_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let alarmy2424 = UIImage(named: "ic_alarmy_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let quick2424 = UIImage(named: "ic_quick_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let ringtone2424 = UIImage(named: "ic_ringtone_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let play2424 = UIImage(named: "ic_play_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let stop2424 = UIImage(named: "ic_stop_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let vibrate2424 = UIImage(named: "ic_vibrate_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let backspace2424 = UIImage(named: "ic_backspace_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let flashOff2424 = UIImage(named: "ic_flashoff_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let flash2424 = UIImage(named: "ic_flash_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let circle2424 = UIImage(named: "ic_circle_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let ok2424 = UIImage(named: "ic_ok_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let caution2424 = UIImage(named: "ic_caution_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let heart2424 = UIImage(named: "ic_heart_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let important2424 = UIImage(named: "ic_important_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let sent2424 = UIImage(named: "ic_sent_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let theme2424 = UIImage(named: "ic_theme_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let bellOn2424 = UIImage(named: "ic_bell_on_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let bellOff2424 = UIImage(named: "ic_bell_off_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let lock2424 = UIImage(named: "ic_lock_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let rocket2424 = UIImage(named: "ic_rocket_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let twitter2424 = UIImage(named: "ic_twitter_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let facebook2424 = UIImage(named: "ic_facebook_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let instagram2424 = UIImage(named: "ic_instagram_24_24", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let soundOn1616 = UIImage(named: "ic_sound_on_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let soundOff1616 = UIImage(named: "ic_sound_off_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let label1616 = UIImage(named: "ic_label_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let snooze1616 = UIImage(named: "ic_snooze_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let alarmy1616 = UIImage(named: "ic_alarmy_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let quick1616 = UIImage(named: "ic_quick_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let ringtone1616 = UIImage(named: "ic_ringtone_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let play1616 = UIImage(named: "ic_play_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let stop1616 = UIImage(named: "ic_stop_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let vibrate1616 = UIImage(named: "ic_vibrate_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let backspace1616 = UIImage(named: "ic_backspace_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let flashOff1616 = UIImage(named: "ic_flashoff_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let flash1616 = UIImage(named: "ic_flash_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let circle1616 = UIImage(named: "ic_circle_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let ok1616 = UIImage(named: "ic_ok_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let caution1616 = UIImage(named: "ic_caution_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let heart1616 = UIImage(named: "ic_heart_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let important1616 = UIImage(named: "ic_important_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let sent1616 = UIImage(named: "ic_sent_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
    public static let theme1616 = UIImage(named: "ic_theme_16_16", in: .module, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
}
